"""Describe compliance rules from configservice"""
import os

from boto3.session import Session


def get_non_compliant_rules():
    """describe compliance by config rule"""
    session = Session(profile_name=os.environ.get("AWS_PROFILE", "default"))
    client = session.client("config")

    paginator = client.get_paginator("describe_compliance_by_config_rule")
    page_iterator = paginator.paginate()

    non_compliant_rules = []

    for page in page_iterator:
        for rule in page["ComplianceByConfigRules"]:
            if rule["Compliance"]["ComplianceType"] == "NON_COMPLIANT":
                non_compliant_rules.append(rule)

    print(f"# report generated by {os.path.basename(__file__)}\n")
    print("| Config Rule Name | Compliance Type | Valuable |")
    print("|------------------|-----------------|----------|")

    for rule in non_compliant_rules:
        print(
            f"| {rule['ConfigRuleName']} | {rule['Compliance']['ComplianceType']} | - [ ] |"
        )


if __name__ == "__main__":
    get_non_compliant_rules()
